version: 0.1
component: build
timeoutInSeconds: 10000
runAs: root
shell: bash
env:
  variables:
    DOCKER_PLATFORM_IMAGE_NAME: "verrazzano-platform-operator-oci-devops"
    DOCKER_OAM_IMAGE_NAME: "verrazzano-application-operator-oci-devops"
    DOCKER_ANALYSIS_IMAGE_NAME: "verrazzano-analysis-oci-devops"
    DOCKER_REPO: "iad.ocir.io"
    DOCKER_NAMESPACE: "odsbuilddev/sandboxes/mark.x.nelson"
    DOCKER_IMAGE_TAG: "ocidevops-1"
    CREATE_LATEST_TAG: "0"

steps:
  - type: Command
    name: "Prepare environment"
    command: |
      echo "hello"
  - type: Command
    name: "Compile"
    command: |
      echo "jon"
      make docker-push \
        VERRAZZANO_PLATFORM_OPERATOR_IMAGE_NAME=${DOCKER_PLATFORM_IMAGE_NAME} \
        VERRAZZANO_APPLICATION_OPERATOR_IMAGE_NAME=${DOCKER_OAM_IMAGE_NAME} \
        VERRAZZANO_ANALYSIS_IMAGE_NAME=${DOCKER_ANALYSIS_IMAGE_NAME} \
        DOCKER_REPO=${DOCKER_REPO} \
        DOCKER_NAMESPACE=${DOCKER_NAMESPACE} \
        DOCKER_IMAGE_TAG=${DOCKER_IMAGE_TAG} \
        CREATE_LATEST_TAG=${CREATE_LATEST_TAG}

outputArtifacts:
  - name: bom
    type: BINARY
    location: Makefile